#!/bin/sh

# dotfiles: a collection of configuration files
# Copyright (c) 2013 Cyphar

# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:

# 1. The above copyright notice and this permission notice shall be included in
#    all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

YES=y
NO=n

option () {
	read -p "${2}" OPTION
	case "${OPTION}" in
		"Y"|"y"|"${YES}")
			eval ${1}=${YES}
			;;
		"N"|"n"|"${NO}")
			eval ${1}=${NO}
			;;
		*)
			# read -i doesn't seem to work, so do it manually
			eval ${1}=${3}
			;;
	esac
}

echo "Choose what to install ($YES/$NO)." 1>&2
option "CLEANUP"	"Clean up old files [$YES]? "			"$YES"
option "BASHCONFIG"	"Install bash configs [$YES]? " 		"$YES"
option "TMUXCONFIG"	"Install tmux configs [$YES]? " 		"$YES"
option "WGETCONFIG"	"Install wget configs [$YES]? " 		"$YES"
option "VIMCONFIG"	"Install vim configs [$YES]? "			"$YES"
option "MOSSCONFIG"	"Install moss configs [$YES]? "			"$YES"
option "GITCONFIG"	"Install git configs [$YES]? "			"$YES"
option "GENSSH"		"Generate a new set of SSH keys [$NO]? "	"$NO"

# clean up any old files
if [ $CLEANUP = $YES ]; then
	echo "*** Cleaning old files ***" 1>&2
	if [ $BASHCONFIG = $YES ]; then
		rm -f $HOME/.bashrc $HOME/.bash_alias $HOME/.profile $HOME/.bash_banner
		rm -f $HOME/.bash_profile $HOME/.bash_login # These stuff up the .profile script
	fi

	if [ $TMUXCONFIG = $YES ]; then
		rm -f $HOME/.tmux.conf
	fi

	if [ $WGETCONFIG = $YES ]; then
		rm -f $HOME/.wgetrc
	fi

	if [ $VIMCONFIG = $YES ]; then
		rm -rf $HOME/.vim/
		rm -f $HOME/.vimrc
	fi

	if [ $MOSSCONFIG = $YES ]; then
		rm -f $HOME/.mossrc
	fi

	if [ $GITCONFIG = $YES ]; then
		rm -f $HOME/.gitconfig
	fi

	if [ $GENSSH = $YES ]; then
		rm -f $HOME/.ssh/id_rsa $HOME/.ssh/id_rsa.pub # Delete RSAv2 keys
		rm -f $HOME/.ssh/identity $HOME/.ssh/identity.pub # Delete RSAv1 keys
		rm -f $HOME/.ssh/id_dsa $HOME/.ssh/id_dsa.pub # Delete DSA keys
	fi
else
	echo "*** WARNING: Skipping cleanup (NOT RECOMMENDED) ***" 1>&2
fi

# install bash configs
if [ $BASHCONFIG = $YES ]; then
	echo "*** Installing bash config ***" 1>&2
	cp .bashrc $HOME/
	cp .bashalias $HOME/
	cp .bashbanner $HOME/
	cp .profile $HOME/
else
	echo "*** Skipped bash config ***" 1>&2
fi

# install tmux configs
if [ $TMUXCONFIG = $YES ]; then
	echo "*** Installing tmux config ***" 1>&2
	cp .tmux.conf $HOME/
else
	echo "*** Skipped tmux config ***" 1>&2
fi

# install wget configs
if [ $WGETCONFIG = $YES ]; then
	echo "*** Installing wget configs ***" 1>&2
	cp .wgetrc $HOME/
else
	echo "*** Skipped wget configs ***" 1>&2
fi

# install vim configs
if [ $VIMCONFIG = $YES ]; then
	echo "*** Installing vim configs ***" 1>&2
	cp .vimrc $HOME/
	cp -r .vim $HOME/
else
	echo "*** Skipped vim configs ***" 1>&2
fi

# install moss configs
if [ $MOSSCONFIG = $YES ]; then
	echo "*** Installing moss configs ***" 1>&2
	cp .mossrc $HOME/
else
	echo "*** Skipped moss configs ***" 1>&2
fi

# install gitconfig
if [ $GITCONFIG = $YES ]; then
	echo "*** Installing gitconfig ***" 1>&2
	cp .gitconfig $HOME/
else
	echo "*** Skipped gitconfig ***" 2>&1
fi

# generate new ssh keys
if [ $GENSSH = $YES ]; then
	echo "*** Generating ssh keys ***" 2>&1
	option "SSHCOMMENT" "Do you want to add your own comment to the key [$NO]? " "$NO"
	if [ $SSHCOMMENT = $YES ]; then
		read -p "Enter comment: " COMMENT
		ssh-keygen -t rsa -b 4096 -C "$COMMENT"
	else
		ssh-keygen -t rsa -b 4096
	fi
else
	echo "*** Skipped ssh keys ***" 2>&1
fi
