#!/bin/zsh
# This is free and unencumbered software released into the public domain.

# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.

# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# Enable alias option completion.
setopt completealiases

# Some weird distros don't symlink vi -> vim.
# This is wrong.
alias vi="vim"
alias vim="nvim"

# ls colours.
alias ls="ls --color=auto"

# ls shortcuts.
alias sl="ls"
alias ll="ls -alF"
alias la="ls -A"
alias l="ls -CF"

# grep colours.
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

# Make valgrind ... work.
alias valgrind="valgrind --leak-check=full --trace-children=yes"
alias vgs="valgrind --read-ver-info=yes"
alias vg="valgrind"

# Make cross-compiling go easier.
function goc() {
	# Get arch as $1.
	local __arch="$1"
	shift

	GOARCH="${__arch}" go $@
}

# Aliases for all archs.
alias go64="goc amd64"
alias go32="goc 386"
alias goarm="goc arm"

# Make setting proxies simpler.
function prox() {
	local __user=$(read -p  "username: "; echo ${REPLY})
	local __pass=$(read -sp "password: "; echo ${REPLY})

	# Deal with no newlines after `read -p`.
	echo

	local __serv=${1-$(read -p  "server: ";   echo ${REPLY})}
	local __prot=${2-$(read -p  "protocol: "; echo ${REPLY})}

	# Create proxy url.
	local __prox="${__prot}://${__user}:${__pass}@${__serv}"

	export HTTP_PROXY="${__prox}"
	export HTTPS_PROXY="${__prox}"
	export SOCKS_PROXY="${__prox}"
	export FTP_PROXY="${__prox}"
	export ALL_PROXY="${__prox}"

	export http_proxy="${__prox}"
	export https_proxy="${__prox}"
	export socks_proxy="${__prox}"
	export ftp_proxy="${__prox}"
	export all_proxy="${__prox}"
}

# Make deactivating proxies simpler.
function unprox() {
	unset HTTP_PROXY HTTPS_PROXY SOCKS_PROXY FTP_PROXY ALL_PROXY
	unset http_proxy https_proxy socks_proxy ftp_proxy all_proxy
}

# Mess around with pico and nano.
alias pico="nano"
function nano() {
	echo "Seriously? Why don't you just use notepad.exe, MS Paint or Edlin?"
}

# Add `time` to `make`, so that we get automagical build script timing
# information, even if you forget to add `time`.
alias make="time make"

# For OBS.
alias iosc="osc -A https://api.suse.de"
alias eosc="osc -A https://api.opensuse.org"

# Nice relative jumps.
alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."
alias ..5="cd ../../../../.."

# Make changing directories easy.
setopt autocd
