#!/bin/zsh
# dotfiles: collection of my personal dotfiles
# Copyright (C) 2012-2019 Aleksa Sarai <cyphar@cyphar.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -Eeuo pipefail

echo "[*] Updating mpvacious."
pushd "$HOME/.config/mpv/scripts/"
MPVACIOUS_VERSION="$(curl -sSL https://api.github.com/repos/Ajatt-Tools/mpvacious/releases/latest | jq -rM .tag_name )"
echo "[-] Installing mpvacious $MPVACIOUS_VERSION"
[[ -d "mpvacious" ]] || git clone https://github.com/Ajatt-Tools/mpvacious.git
pushd "mpvacious"
git fetch origin
git reset --hard HEAD
git checkout "$MPVACIOUS_VERSION"
popd

echo "[*] Updating youtube-dl (yt-dlp)."
if ! ( command yt-dlp --version &>/dev/null ); then
	YTDL_VERSION="$(curl -sSL https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest | jq -rM .tag_name )"
	echo "[-] Installing yt-dlp $YTDL_VERSION."
	pushd "$HOME/.local/bin"
	curl -SLo yt-dlp "https://github.com/yt-dlp/yt-dlp/releases/download/$YTDL_VERSION/yt-dlp"
	chmod +x yt-dlp
	popd
else
	yt-dlp -U
fi
