#!/bin/zsh
# dotfiles: collection of my personal dotfiles [code]
# Copyright (C) 2012-2017 Aleksa Sarai <cyphar@cyphar.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# In order to make sure that $GOPATH acts correctly, we have to add quite a few
# symlinks. Unfortunately this is quite ugly. Everything ends up being under
# $HOME/.local so that Go's lovely $GOPATH/pkg bullshit doesn't pollute my
# $HOME. We then make a symlink from $HOME/src to make things act nicer -- and
# inside $HOME/.zshrc $CDPATH is set to make changing into Go projects a bit
# less of a pain.

function abort() {
	echo $* >&2
	exit 1
}

[[ -z "$GOPATH" ]] && abort '$GOPATH not set!'
[[ -e "$HOME/src" && ! -L "$HOME/src" ]] && abort '$HOME/src exists but is not a symlink!'
[[ -L "$GOPATH/src" ]] && rm "$GOPATH/src"

mkdir -p "$GOPATH/src"
rm -f "$HOME/src"
ln -sf "$GOPATH/src" "$HOME/src"
