#!/bin/zsh
# dotfiles: collection of my personal dotfiles [code]
# Copyright (C) 2012-2016 Aleksa Sarai <cyphar@cyphar.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function abort() {
	echo $* 1>&2
	exit 1
}

# Make sure $GOPATH works.
[[ -z "$GOPATH" ]] && abort '$GOPATH not set!'
[[ "$GOPATH" == "$HOME" ]] && exit 0

# $GOPATH/src should always link to $HOME/src
[[ -L "$GOPATH/src" ]] && rm "$GOPATH/src"
[[ -e "$GOPATH/src" ]] && rm -rf "$GOPATH/src"
ln -sf "$HOME/src" "$GOPATH/src"
